Fix style errors
RWOverdijk/jw-showcase-lib pull request #3
Opened 2017-08-01 08:46 UTC by brniamut

2017-08-18 08:04 UTC, brniamut commented
@RWOverdijk, Don't see a way to add a reviewer so I'm just tagging you like this.

2017-08-18 08:52 UTC, RWOverdijk requested changes

2017-08-18 08:52 UTC, RWOverdijk commented on scss/components/_popups.scss
> +
Remove newline? Or is this on purpose?

2017-08-18 10:25 UTC, brniamut commented on scss/components/_popups.scss
> +
No this was not on purpose. Fixed.

2017-08-21 08:29 UTC, RWOverdijk approved these changes

2017-08-21 08:33 UTC, merged